name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: gcc -v
    - run: make

  build-linux-meson:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install meson ninja
    - run: gcc -v
    - run: meson setup builddir/
      env:
        CC: gcc
    - run: meson compile -C builddir/

  build-wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: clang -v
    - run: make CC="clang --target=wasm32"
    - uses: actions/upload-artifact@v4
      with:
        name: liblc3.wasm
        path: bin/liblc3.wasm

  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install scipy numpy
    - run: gcc -v
    - run: make test

  install-python-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: pip install .
